INSERT INTO instruments (station_id, canonical_id, legacy_name, instrument_type, ecosystem, platform_code, instrument_number, status, deployment_date, platform_mounting_structure, platform_height_m, instrument_height_m, viewing_direction, azimuth_degrees, degrees_from_nadir, latitude, longitude, geolocation_notes, sensor_type, wavelengths, sensor_pairs) VALUES (1, 'ANS_FOR_BL01_PHE01', 'ANS-FOR-P01', 'phenocam', 'FOR', 'BL01', 'PHE01', 'Active', NULL, 'Building RoofTop', 4.5, 4.5, 'West', 270, 90, 68.353729, 18.816522, NULL, NULL, NULL, NULL);

INSERT INTO instruments (station_id, canonical_id, legacy_name, instrument_type, ecosystem, platform_code, instrument_number, status, deployment_date, platform_mounting_structure, platform_height_m, instrument_height_m, viewing_direction, azimuth_degrees, degrees_from_nadir, latitude, longitude, geolocation_notes, sensor_type, wavelengths, sensor_pairs) VALUES (2, 'GRI_FOR_BL01_PHE01', 'GRI-FOR-P01', 'phenocam', 'FOR', 'BL01', 'PHE01', 'Active', NULL, 'Building Wall', 4, 3.5, NULL, NULL, 90, 59.72868, 15.47249, NULL, NULL, NULL, NULL);

INSERT INTO instruments (station_id, canonical_id, legacy_name, instrument_type, ecosystem, platform_code, instrument_number, status, deployment_date, platform_mounting_structure, platform_height_m, instrument_height_m, viewing_direction, azimuth_degrees, degrees_from_nadir, latitude, longitude, geolocation_notes, sensor_type, wavelengths, sensor_pairs) VALUES (3, 'LON_AGR_PL01_PHE01', 'SFA-AGR-P01', 'phenocam', 'AGR', 'PL01', 'PHE01', 'Active', NULL, 'Mast', 10, 10, 'West-North-West', 293, 58, 55.668731, 13.108632, NULL, NULL, NULL, NULL);

INSERT INTO instruments (station_id, canonical_id, legacy_name, instrument_type, ecosystem, platform_code, instrument_number, status, deployment_date, platform_mounting_structure, platform_height_m, instrument_height_m, viewing_direction, azimuth_degrees, degrees_from_nadir, latitude, longitude, geolocation_notes, sensor_type, wavelengths, sensor_pairs) VALUES (3, 'LON_AGR_PL01_PHE02', 'SFA-AGR-P02', 'phenocam', 'AGR', 'PL01', 'PHE02', 'Active', NULL, 'Mast', 10, 10, 'North', 12, 58, 55.669186, 13.11036, NULL, NULL, NULL, NULL);

INSERT INTO instruments (station_id, canonical_id, legacy_name, instrument_type, ecosystem, platform_code, instrument_number, status, deployment_date, platform_mounting_structure, platform_height_m, instrument_height_m, viewing_direction, azimuth_degrees, degrees_from_nadir, latitude, longitude, geolocation_notes, sensor_type, wavelengths, sensor_pairs) VALUES (3, 'LON_AGR_PL01_PHE03', 'SFA-AGR-P03', 'phenocam', 'AGR', 'PL01', 'PHE03', 'Active', NULL, 'Mast', 10, 10, 'East', 85, 58, 55.668549, 13.110535, NULL, NULL, NULL, NULL);

INSERT INTO instruments (station_id, canonical_id, legacy_name, instrument_type, ecosystem, platform_code, instrument_number, status, deployment_date, platform_mounting_structure, platform_height_m, instrument_height_m, viewing_direction, azimuth_degrees, degrees_from_nadir, latitude, longitude, geolocation_notes, sensor_type, wavelengths, sensor_pairs) VALUES (4, 'RBD_AGR_PL01_PHE01', 'RBD-AGR-P01', 'phenocam', 'AGR', 'PL01', 'PHE01', 'Active', NULL, 'Mast', 10, 10, 'West', 265, 59, 63.806642, 20.229243, NULL, NULL, NULL, NULL);

INSERT INTO instruments (station_id, canonical_id, legacy_name, instrument_type, ecosystem, platform_code, instrument_number, status, deployment_date, platform_mounting_structure, platform_height_m, instrument_height_m, viewing_direction, azimuth_degrees, degrees_from_nadir, latitude, longitude, geolocation_notes, sensor_type, wavelengths, sensor_pairs) VALUES (4, 'RBD_AGR_PL02_PHE01', 'RBD-AGR-P02', 'phenocam', 'AGR', 'PL02', 'PHE01', 'Active', NULL, 'Mast', 4, 4, 'West', 305, 59, 63.809992, 20.238822, NULL, NULL, NULL, NULL);

INSERT INTO instruments (station_id, canonical_id, legacy_name, instrument_type, ecosystem, platform_code, instrument_number, status, deployment_date, platform_mounting_structure, platform_height_m, instrument_height_m, viewing_direction, azimuth_degrees, degrees_from_nadir, latitude, longitude, geolocation_notes, sensor_type, wavelengths, sensor_pairs) VALUES (5, 'SKC_CEM_FOR_PL01_PHE01', 'CEM01-FOR-P01', 'phenocam', 'FOR', 'PL01', 'PHE01', 'Active', NULL, 'Tower', 38, 38, 'South', 185, 38, 58.363865, 12.149763, NULL, NULL, NULL, NULL);

INSERT INTO instruments (station_id, canonical_id, legacy_name, instrument_type, ecosystem, platform_code, instrument_number, status, deployment_date, platform_mounting_structure, platform_height_m, instrument_height_m, viewing_direction, azimuth_degrees, degrees_from_nadir, latitude, longitude, geolocation_notes, sensor_type, wavelengths, sensor_pairs) VALUES (5, 'SKC_CEM_FOR_PL02_PHE01', 'CEM02-FOR-P02', 'phenocam', 'FOR', 'PL02', 'PHE01', 'Active', NULL, 'Mast', 3, 3, 'West', 270, 47, 58.363759, 12.149442, NULL, NULL, NULL, NULL);

INSERT INTO instruments (station_id, canonical_id, legacy_name, instrument_type, ecosystem, platform_code, instrument_number, status, deployment_date, platform_mounting_structure, platform_height_m, instrument_height_m, viewing_direction, azimuth_degrees, degrees_from_nadir, latitude, longitude, geolocation_notes, sensor_type, wavelengths, sensor_pairs) VALUES (5, 'SKC_CEM_FOR_PL03_PHE01', 'CEM03-FOR-P03', 'phenocam', 'FOR', 'PL03', 'PHE01', 'Active', NULL, 'Mast', 3, 3, 'West?', 270?, 42, 58.363596, 12.149933, NULL, NULL, NULL, NULL);

INSERT INTO instruments (station_id, canonical_id, legacy_name, instrument_type, ecosystem, platform_code, instrument_number, status, deployment_date, platform_mounting_structure, platform_height_m, instrument_height_m, viewing_direction, azimuth_degrees, degrees_from_nadir, latitude, longitude, geolocation_notes, sensor_type, wavelengths, sensor_pairs) VALUES (5, 'SKC_LAK_PL01_PHE01', 'ERS-LAK-P01', 'phenocam', 'LAK', 'PL01', 'PHE01', 'Active', NULL, 'Mast', 38, 38, 'South', 185, 38, 58.363058, 12.14965, NULL, NULL, NULL, NULL);

INSERT INTO instruments (station_id, canonical_id, legacy_name, instrument_type, ecosystem, platform_code, instrument_number, status, deployment_date, platform_mounting_structure, platform_height_m, instrument_height_m, viewing_direction, azimuth_degrees, degrees_from_nadir, latitude, longitude, geolocation_notes, sensor_type, wavelengths, sensor_pairs) VALUES (5, 'STM_FOR_PL01_PHE01', 'STM-FOR-P01', 'phenocam', 'FOR', 'PL01', 'PHE01', 'Active', NULL, 'Mast', NULL, NULL, NULL, NULL, NULL, 58.368601, 12.145319, 'URGENT REQUIRES NAME AND LOCATION used Phenocam Replanted, C-mast-5, MCM05 because missing info', NULL, NULL, NULL);

INSERT INTO instruments (station_id, canonical_id, legacy_name, instrument_type, ecosystem, platform_code, instrument_number, status, deployment_date, platform_mounting_structure, platform_height_m, instrument_height_m, viewing_direction, azimuth_degrees, degrees_from_nadir, latitude, longitude, geolocation_notes, sensor_type, wavelengths, sensor_pairs) VALUES (5, 'SKC_MAD_WET_PL01_PHE01', 'MAD-WET-P01', 'phenocam', 'WET', 'PL02', 'PHE01', 'Active', NULL, 'Mast', NULL, NULL, NULL, NULL, NULL, 58.368601, 12.145319, 'URGENT NAME AND LOCATION CONFIRMATION', NULL, NULL, NULL);

INSERT INTO instruments (station_id, canonical_id, legacy_name, instrument_type, ecosystem, platform_code, instrument_number, status, deployment_date, platform_mounting_structure, platform_height_m, instrument_height_m, viewing_direction, azimuth_degrees, degrees_from_nadir, latitude, longitude, geolocation_notes, sensor_type, wavelengths, sensor_pairs) VALUES (5, 'SKC_MAD_FOR_PL02_PHE01', 'MAD-FOR-P01', 'phenocam', 'FOR', 'PL04', 'PHE01', 'Active', NULL, 'Mast', NULL, NULL, NULL, NULL, NULL, 58.368601, 12.145319, 'URGENT NAME AND LOCATION CONFIRMATION', NULL, NULL, NULL);

INSERT INTO instruments (station_id, canonical_id, legacy_name, instrument_type, ecosystem, platform_code, instrument_number, status, deployment_date, platform_mounting_structure, platform_height_m, instrument_height_m, viewing_direction, azimuth_degrees, degrees_from_nadir, latitude, longitude, geolocation_notes, sensor_type, wavelengths, sensor_pairs) VALUES (5, 'SKC_SRC_FOL_WET_PL01_PHE01', 'FOL-WET-P01', 'phenocam', 'WET', 'PL03', 'PHE01', 'Active', NULL, 'Mast', NULL, NULL, NULL, NULL, NULL, 58.375661, 12.154016, NULL, NULL, NULL, NULL);

INSERT INTO instruments (station_id, canonical_id, legacy_name, instrument_type, ecosystem, platform_code, instrument_number, status, deployment_date, platform_mounting_structure, platform_height_m, instrument_height_m, viewing_direction, azimuth_degrees, degrees_from_nadir, latitude, longitude, geolocation_notes, sensor_type, wavelengths, sensor_pairs) VALUES (5, 'SKC_SRC_FOL_WET_PL02_PHE01', 'FOL-WET-P02', 'phenocam', 'WET', 'PL04', 'PHE01', 'Active', NULL, 'Mast', NULL, NULL, NULL, NULL, NULL, 58.375854, 12.154016, NULL, NULL, NULL, NULL);

INSERT INTO instruments (station_id, canonical_id, legacy_name, instrument_type, ecosystem, platform_code, instrument_number, status, deployment_date, platform_mounting_structure, platform_height_m, instrument_height_m, viewing_direction, azimuth_degrees, degrees_from_nadir, latitude, longitude, geolocation_notes, sensor_type, wavelengths, sensor_pairs) VALUES (6, 'SVB_MIR_PL01_PHE01', 'DEG-MIR-P01', 'phenocam', 'MIR', 'PL01', 'PHE01', 'Active', NULL, NULL, 17.5, 17.5, 'North-NorthEast', 317, 81, 64.182536, 19.558045, NULL, NULL, NULL, NULL);

INSERT INTO instruments (station_id, canonical_id, legacy_name, instrument_type, ecosystem, platform_code, instrument_number, status, deployment_date, platform_mounting_structure, platform_height_m, instrument_height_m, viewing_direction, azimuth_degrees, degrees_from_nadir, latitude, longitude, geolocation_notes, sensor_type, wavelengths, sensor_pairs) VALUES (6, 'SVB_MIR_PL02_PHE01', 'DEG-MIR-P02', 'phenocam', 'MIR', 'PL02', 'PHE01', 'Active', NULL, 'Mast', 3.3, 3.3, 'North', 343, 82, 64.18201, 19.556576, NULL, NULL, NULL, NULL);

INSERT INTO instruments (station_id, canonical_id, legacy_name, instrument_type, ecosystem, platform_code, instrument_number, status, deployment_date, platform_mounting_structure, platform_height_m, instrument_height_m, viewing_direction, azimuth_degrees, degrees_from_nadir, latitude, longitude, geolocation_notes, sensor_type, wavelengths, sensor_pairs) VALUES (6, 'SVB_MIR_PL03_PHE01', 'DEG-MIR-P03', 'phenocam', 'MIR', 'PL03', 'PHE01', 'Active', 'Tue Oct 29 2024 01:00:00 GMT+0100 (Central European Standard Time)', 'Mast', 17.5, 17.5, 'North-NorthEast', 317, 81, 64.182536, 19.558045, NULL, NULL, NULL, NULL);

INSERT INTO instruments (station_id, canonical_id, legacy_name, instrument_type, ecosystem, platform_code, instrument_number, status, deployment_date, platform_mounting_structure, platform_height_m, instrument_height_m, viewing_direction, azimuth_degrees, degrees_from_nadir, latitude, longitude, geolocation_notes, sensor_type, wavelengths, sensor_pairs) VALUES (6, 'SVB_FOR_PL01_PHE01', 'SVB-FOR-P01', 'phenocam', 'FOR', 'PL01', 'PHE01', 'Inactive', NULL, 'Flagpole', 70, 70, 'North-West', 280, 45, 64.256342, 19.771621, NULL, NULL, NULL, NULL);

INSERT INTO instruments (station_id, canonical_id, legacy_name, instrument_type, ecosystem, platform_code, instrument_number, status, deployment_date, platform_mounting_structure, platform_height_m, instrument_height_m, viewing_direction, azimuth_degrees, degrees_from_nadir, latitude, longitude, geolocation_notes, sensor_type, wavelengths, sensor_pairs) VALUES (6, 'SVB_FOR_PL01_PHE02', 'SVB-FOR-P02', 'phenocam', 'FOR', 'PL01', 'PHE02', 'Active', 'Tue Oct 29 2024 01:00:00 GMT+0100 (Central European Standard Time)', 'Tower', 70, 70, 'North-West', 280, 45, 64.256342, 19.771621, NULL, NULL, NULL, NULL);

INSERT INTO instruments (station_id, canonical_id, legacy_name, instrument_type, ecosystem, platform_code, instrument_number, status, deployment_date, platform_mounting_structure, platform_height_m, instrument_height_m, viewing_direction, azimuth_degrees, degrees_from_nadir, latitude, longitude, geolocation_notes, sensor_type, wavelengths, sensor_pairs) VALUES (1, 'ANS_HEA_F01_MS01', 'MJA-HEA-F01', 'fixed_sensor', 'HEA', 'F01', 'MS01', 'Active', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO instruments (station_id, canonical_id, legacy_name, instrument_type, ecosystem, platform_code, instrument_number, status, deployment_date, platform_mounting_structure, platform_height_m, instrument_height_m, viewing_direction, azimuth_degrees, degrees_from_nadir, latitude, longitude, geolocation_notes, sensor_type, wavelengths, sensor_pairs) VALUES (1, 'ANS_SFO_MS01', 'NordSpec_SFO', 'fixed_sensor', 'SFO', NULL, 'MS01', 'Active', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO instruments (station_id, canonical_id, legacy_name, instrument_type, ecosystem, platform_code, instrument_number, status, deployment_date, platform_mounting_structure, platform_height_m, instrument_height_m, viewing_direction, azimuth_degrees, degrees_from_nadir, latitude, longitude, geolocation_notes, sensor_type, wavelengths, sensor_pairs) VALUES (1, 'ANS_MIR_F01_MS01', 'SMS-MIR-F01', 'fixed_sensor', 'MIR', 'F01', 'MS01', 'Active', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO instruments (station_id, canonical_id, legacy_name, instrument_type, ecosystem, platform_code, instrument_number, status, deployment_date, platform_mounting_structure, platform_height_m, instrument_height_m, viewing_direction, azimuth_degrees, degrees_from_nadir, latitude, longitude, geolocation_notes, sensor_type, wavelengths, sensor_pairs) VALUES (4, 'RBD_AGR_F01_MS01', 'RBD-AGR-F01', 'fixed_sensor', 'AGR', 'F01', 'MS01', 'Active', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Skye', '[644,858]', '["sky_ground"]');

INSERT INTO instruments (station_id, canonical_id, legacy_name, instrument_type, ecosystem, platform_code, instrument_number, status, deployment_date, platform_mounting_structure, platform_height_m, instrument_height_m, viewing_direction, azimuth_degrees, degrees_from_nadir, latitude, longitude, geolocation_notes, sensor_type, wavelengths, sensor_pairs) VALUES (4, 'RBD_AGR_F02_MS01', 'RBD-AGR-F02', 'fixed_sensor', 'AGR', 'F02', 'MS01', 'Active', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '[644,858]', '["sky_ground"]');

INSERT INTO instruments (station_id, canonical_id, legacy_name, instrument_type, ecosystem, platform_code, instrument_number, status, deployment_date, platform_mounting_structure, platform_height_m, instrument_height_m, viewing_direction, azimuth_degrees, degrees_from_nadir, latitude, longitude, geolocation_notes, sensor_type, wavelengths, sensor_pairs) VALUES (3, 'LON_AGR_F01_MS01', 'SFA-AGR-F01', 'fixed_sensor', 'AGR', 'F01', 'MS01', 'Active', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO instruments (station_id, canonical_id, legacy_name, instrument_type, ecosystem, platform_code, instrument_number, status, deployment_date, platform_mounting_structure, platform_height_m, instrument_height_m, viewing_direction, azimuth_degrees, degrees_from_nadir, latitude, longitude, geolocation_notes, sensor_type, wavelengths, sensor_pairs) VALUES (3, 'LON_AGR_F02_MS01', 'SFA-AGR-F02', 'fixed_sensor', 'AGR', 'F02', 'MS01', 'Active', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO instruments (station_id, canonical_id, legacy_name, instrument_type, ecosystem, platform_code, instrument_number, status, deployment_date, platform_mounting_structure, platform_height_m, instrument_height_m, viewing_direction, azimuth_degrees, degrees_from_nadir, latitude, longitude, geolocation_notes, sensor_type, wavelengths, sensor_pairs) VALUES (6, 'SVB_MIR_F01_MS01', 'DEG-MIR-F01', 'fixed_sensor', 'MIR', 'F01', 'MS01', 'Active', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO instruments (station_id, canonical_id, legacy_name, instrument_type, ecosystem, platform_code, instrument_number, status, deployment_date, platform_mounting_structure, platform_height_m, instrument_height_m, viewing_direction, azimuth_degrees, degrees_from_nadir, latitude, longitude, geolocation_notes, sensor_type, wavelengths, sensor_pairs) VALUES (6, 'SVB_FOR_F01_MS01', 'SVB-FOR-F01', 'fixed_sensor', 'FOR', 'F01', 'MS01', 'Active', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO instruments (station_id, canonical_id, legacy_name, instrument_type, ecosystem, platform_code, instrument_number, status, deployment_date, platform_mounting_structure, platform_height_m, instrument_height_m, viewing_direction, azimuth_degrees, degrees_from_nadir, latitude, longitude, geolocation_notes, sensor_type, wavelengths, sensor_pairs) VALUES (5, 'SKG_FOR_F01_MS01', 'CEN-FOR-F01', 'fixed_sensor', 'FOR', 'F01', 'MS01', 'Active', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO instruments (station_id, canonical_id, legacy_name, instrument_type, ecosystem, platform_code, instrument_number, status, deployment_date, platform_mounting_structure, platform_height_m, instrument_height_m, viewing_direction, azimuth_degrees, degrees_from_nadir, latitude, longitude, geolocation_notes, sensor_type, wavelengths, sensor_pairs) VALUES (5, 'SKG_FOR_F02_MS01', 'CEN-FOR-F02', 'fixed_sensor', 'FOR', 'F02', 'MS01', 'Active', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO instruments (station_id, canonical_id, legacy_name, instrument_type, ecosystem, platform_code, instrument_number, status, deployment_date, platform_mounting_structure, platform_height_m, instrument_height_m, viewing_direction, azimuth_degrees, degrees_from_nadir, latitude, longitude, geolocation_notes, sensor_type, wavelengths, sensor_pairs) VALUES (5, 'SKG_FOR_F03_MS01', 'CEN-FOR-F03', 'fixed_sensor', 'FOR', 'F03', 'MS01', 'Active', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO instruments (station_id, canonical_id, legacy_name, instrument_type, ecosystem, platform_code, instrument_number, status, deployment_date, platform_mounting_structure, platform_height_m, instrument_height_m, viewing_direction, azimuth_degrees, degrees_from_nadir, latitude, longitude, geolocation_notes, sensor_type, wavelengths, sensor_pairs) VALUES (5, 'SKG_WET_F01_MS01', 'FOL-WET-F01', 'fixed_sensor', 'WET', 'F01', 'MS01', 'Active', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO instruments (station_id, canonical_id, legacy_name, instrument_type, ecosystem, platform_code, instrument_number, status, deployment_date, platform_mounting_structure, platform_height_m, instrument_height_m, viewing_direction, azimuth_degrees, degrees_from_nadir, latitude, longitude, geolocation_notes, sensor_type, wavelengths, sensor_pairs) VALUES (5, 'SKG_MIR_F01_MS01', 'MYC-MIR-F01', 'fixed_sensor', 'MIR', 'F01', 'MS01', 'Active', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO instruments (station_id, canonical_id, legacy_name, instrument_type, ecosystem, platform_code, instrument_number, status, deployment_date, platform_mounting_structure, platform_height_m, instrument_height_m, viewing_direction, azimuth_degrees, degrees_from_nadir, latitude, longitude, geolocation_notes, sensor_type, wavelengths, sensor_pairs) VALUES (5, 'SKG_FOR_STD_MS01', 'STD-FOR-F01', 'fixed_sensor', 'FOR', 'STD', 'MS01', 'Active', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);