INSERT INTO mspectral_sensors (
    station_id, canonical_id, legacy_name, sensor_type, ecosystem, location, status, deployment_date,
    latitude, longitude, elevation_m, brand, model, serial_number, cable_length, honxiao_number,
    center_wavelength_nm, bandwidth_nm, field_of_view_degrees, azimuth_degrees, degrees_from_nadir,
    measurement_type, usage_type, parameter_names, wavelengths_nm, sensor_pairs, comments
  ) VALUES (
    1,
    'ANS_HEA_F01_MS01',
    'MJA-HEA-F01',
    'SPECTRAL',
    'HEA',
    'F01',
    'Active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );

INSERT INTO mspectral_sensors (
    station_id, canonical_id, legacy_name, sensor_type, ecosystem, location, status, deployment_date,
    latitude, longitude, elevation_m, brand, model, serial_number, cable_length, honxiao_number,
    center_wavelength_nm, bandwidth_nm, field_of_view_degrees, azimuth_degrees, degrees_from_nadir,
    measurement_type, usage_type, parameter_names, wavelengths_nm, sensor_pairs, comments
  ) VALUES (
    1,
    'ANS_SFO_MS01',
    'NordSpec_SFO',
    'SPECTRAL',
    'SFO',
    NULL,
    'Active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );

INSERT INTO mspectral_sensors (
    station_id, canonical_id, legacy_name, sensor_type, ecosystem, location, status, deployment_date,
    latitude, longitude, elevation_m, brand, model, serial_number, cable_length, honxiao_number,
    center_wavelength_nm, bandwidth_nm, field_of_view_degrees, azimuth_degrees, degrees_from_nadir,
    measurement_type, usage_type, parameter_names, wavelengths_nm, sensor_pairs, comments
  ) VALUES (
    1,
    'ANS_MIR_F01_MS01',
    'SMS-MIR-F01',
    'SPECTRAL',
    'MIR',
    'F01',
    'Active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );

INSERT INTO mspectral_sensors (
    station_id, canonical_id, legacy_name, sensor_type, ecosystem, location, status, deployment_date,
    latitude, longitude, elevation_m, brand, model, serial_number, cable_length, honxiao_number,
    center_wavelength_nm, bandwidth_nm, field_of_view_degrees, azimuth_degrees, degrees_from_nadir,
    measurement_type, usage_type, parameter_names, wavelengths_nm, sensor_pairs, comments
  ) VALUES (
    4,
    'RBD_AGR_F01_MS01',
    'RBD-AGR-F01',
    'SPECTRAL',
    'AGR',
    'F01',
    'Active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[644,858]',
    '[sky_ground]',
    NULL
  );

INSERT INTO mspectral_sensors (
    station_id, canonical_id, legacy_name, sensor_type, ecosystem, location, status, deployment_date,
    latitude, longitude, elevation_m, brand, model, serial_number, cable_length, honxiao_number,
    center_wavelength_nm, bandwidth_nm, field_of_view_degrees, azimuth_degrees, degrees_from_nadir,
    measurement_type, usage_type, parameter_names, wavelengths_nm, sensor_pairs, comments
  ) VALUES (
    4,
    'RBD_AGR_F02_MS01',
    'RBD-AGR-F02',
    'SPECTRAL',
    'AGR',
    'F02',
    'Active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '[644,858]',
    '[sky_ground]',
    NULL
  );

INSERT INTO mspectral_sensors (
    station_id, canonical_id, legacy_name, sensor_type, ecosystem, location, status, deployment_date,
    latitude, longitude, elevation_m, brand, model, serial_number, cable_length, honxiao_number,
    center_wavelength_nm, bandwidth_nm, field_of_view_degrees, azimuth_degrees, degrees_from_nadir,
    measurement_type, usage_type, parameter_names, wavelengths_nm, sensor_pairs, comments
  ) VALUES (
    3,
    'LON_AGR_F01_MS01',
    'SFA-AGR-F01',
    'SPECTRAL',
    'AGR',
    'F01',
    'Active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );

INSERT INTO mspectral_sensors (
    station_id, canonical_id, legacy_name, sensor_type, ecosystem, location, status, deployment_date,
    latitude, longitude, elevation_m, brand, model, serial_number, cable_length, honxiao_number,
    center_wavelength_nm, bandwidth_nm, field_of_view_degrees, azimuth_degrees, degrees_from_nadir,
    measurement_type, usage_type, parameter_names, wavelengths_nm, sensor_pairs, comments
  ) VALUES (
    3,
    'LON_AGR_F02_MS01',
    'SFA-AGR-F02',
    'SPECTRAL',
    'AGR',
    'F02',
    'Active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );

INSERT INTO mspectral_sensors (
    station_id, canonical_id, legacy_name, sensor_type, ecosystem, location, status, deployment_date,
    latitude, longitude, elevation_m, brand, model, serial_number, cable_length, honxiao_number,
    center_wavelength_nm, bandwidth_nm, field_of_view_degrees, azimuth_degrees, degrees_from_nadir,
    measurement_type, usage_type, parameter_names, wavelengths_nm, sensor_pairs, comments
  ) VALUES (
    6,
    'SVB_MIR_F01_MS01_1',
    'DEG-MIR-F01',
    'SPECTRAL',
    'MIR',
    'F01',
    'Active',
    NULL,
    64.182536,
    19.558045,
    17.5,
    'SKYE',
    'SKR1860  D/A/X',
    NULL,
    NULL,
    46436,
    704.2,
    10.5,
    25,
    317,
    45,
    'outgoing',
    '?',
    'Dw_704_1_Avg',
    NULL,
    NULL,
    NULL
  );

INSERT INTO mspectral_sensors (
    station_id, canonical_id, legacy_name, sensor_type, ecosystem, location, status, deployment_date,
    latitude, longitude, elevation_m, brand, model, serial_number, cable_length, honxiao_number,
    center_wavelength_nm, bandwidth_nm, field_of_view_degrees, azimuth_degrees, degrees_from_nadir,
    measurement_type, usage_type, parameter_names, wavelengths_nm, sensor_pairs, comments
  ) VALUES (
    6,
    'SVB_MIR_F01_MS01_2',
    'DEG-MIR-F01',
    'SPECTRAL',
    'MIR',
    'F01',
    'Active',
    NULL,
    64.182536,
    19.558045,
    17.5,
    'SKYE',
    'SKR1860  D/A/X',
    NULL,
    NULL,
    46436,
    740,
    10.3,
    25,
    317,
    45,
    'outgoing',
    '?',
    'Dw_740_1_Avg',
    NULL,
    NULL,
    NULL
  );

INSERT INTO mspectral_sensors (
    station_id, canonical_id, legacy_name, sensor_type, ecosystem, location, status, deployment_date,
    latitude, longitude, elevation_m, brand, model, serial_number, cable_length, honxiao_number,
    center_wavelength_nm, bandwidth_nm, field_of_view_degrees, azimuth_degrees, degrees_from_nadir,
    measurement_type, usage_type, parameter_names, wavelengths_nm, sensor_pairs, comments
  ) VALUES (
    6,
    'SVB_MIR_F01_MS01_3',
    'DEG-MIR-F01',
    'SPECTRAL',
    'MIR',
    'F01',
    'Active',
    NULL,
    64.182536,
    19.558045,
    17.5,
    'SKYE',
    'SKR1860  D/A/X',
    NULL,
    NULL,
    46436,
    858.4,
    38.1,
    25,
    317,
    45,
    'outgoing',
    '?',
    'Dw_858_1_Avg',
    NULL,
    NULL,
    NULL
  );

INSERT INTO mspectral_sensors (
    station_id, canonical_id, legacy_name, sensor_type, ecosystem, location, status, deployment_date,
    latitude, longitude, elevation_m, brand, model, serial_number, cable_length, honxiao_number,
    center_wavelength_nm, bandwidth_nm, field_of_view_degrees, azimuth_degrees, degrees_from_nadir,
    measurement_type, usage_type, parameter_names, wavelengths_nm, sensor_pairs, comments
  ) VALUES (
    6,
    'SVB_MIR_F01_MS01_4',
    'DEG-MIR-F01',
    'SPECTRAL',
    'MIR',
    'F01',
    'Active',
    NULL,
    64.182536,
    19.558045,
    17.5,
    'SKYE',
    'SKR1860  D/A/X',
    NULL,
    NULL,
    46436,
    1640.7,
    21.7,
    25,
    317,
    45,
    'outgoing',
    '?',
    'Dw_1640_1_Avg',
    NULL,
    NULL,
    NULL
  );

INSERT INTO mspectral_sensors (
    station_id, canonical_id, legacy_name, sensor_type, ecosystem, location, status, deployment_date,
    latitude, longitude, elevation_m, brand, model, serial_number, cable_length, honxiao_number,
    center_wavelength_nm, bandwidth_nm, field_of_view_degrees, azimuth_degrees, degrees_from_nadir,
    measurement_type, usage_type, parameter_names, wavelengths_nm, sensor_pairs, comments
  ) VALUES (
    6,
    'SVB_MIR_F01_MS01_5',
    'DEG-MIR-F01',
    'SPECTRAL',
    'MIR',
    'F01',
    'Active',
    NULL,
    64.182536,
    19.558045,
    17.5,
    'SKYE',
    'SKR1860  D/A/X',
    NULL,
    NULL,
    46436,
    NULL,
    NULL,
    25,
    317,
    45,
    'outgoing',
    '?',
    'Dw_Temp_18m_1_Var',
    NULL,
    NULL,
    NULL
  );

INSERT INTO mspectral_sensors (
    station_id, canonical_id, legacy_name, sensor_type, ecosystem, location, status, deployment_date,
    latitude, longitude, elevation_m, brand, model, serial_number, cable_length, honxiao_number,
    center_wavelength_nm, bandwidth_nm, field_of_view_degrees, azimuth_degrees, degrees_from_nadir,
    measurement_type, usage_type, parameter_names, wavelengths_nm, sensor_pairs, comments
  ) VALUES (
    6,
    'SVB_MIR_F01_MS01_6',
    'DEG-MIR-F01',
    'SPECTRAL',
    'MIR',
    'F01',
    'Active',
    NULL,
    64.182536,
    19.558045,
    17.5,
    'SKYE',
    'SKR1860  D/A/X',
    NULL,
    NULL,
    46434,
    704.5,
    10.5,
    25,
    NULL,
    180,
    'incoming',
    '?',
    'Up_704_1_Avg',
    NULL,
    NULL,
    NULL
  );

INSERT INTO mspectral_sensors (
    station_id, canonical_id, legacy_name, sensor_type, ecosystem, location, status, deployment_date,
    latitude, longitude, elevation_m, brand, model, serial_number, cable_length, honxiao_number,
    center_wavelength_nm, bandwidth_nm, field_of_view_degrees, azimuth_degrees, degrees_from_nadir,
    measurement_type, usage_type, parameter_names, wavelengths_nm, sensor_pairs, comments
  ) VALUES (
    6,
    'SVB_MIR_F01_MS01_7',
    'DEG-MIR-F01',
    'SPECTRAL',
    'MIR',
    'F01',
    'Active',
    NULL,
    64.182536,
    19.558045,
    17.5,
    'SKYE',
    'SKR1860  D/A/X',
    NULL,
    NULL,
    46434,
    740.2,
    10.3,
    25,
    NULL,
    180,
    'incoming',
    '?',
    'Up_740_1_Avg',
    NULL,
    NULL,
    NULL
  );

INSERT INTO mspectral_sensors (
    station_id, canonical_id, legacy_name, sensor_type, ecosystem, location, status, deployment_date,
    latitude, longitude, elevation_m, brand, model, serial_number, cable_length, honxiao_number,
    center_wavelength_nm, bandwidth_nm, field_of_view_degrees, azimuth_degrees, degrees_from_nadir,
    measurement_type, usage_type, parameter_names, wavelengths_nm, sensor_pairs, comments
  ) VALUES (
    6,
    'SVB_MIR_F01_MS01_8',
    'DEG-MIR-F01',
    'SPECTRAL',
    'MIR',
    'F01',
    'Active',
    NULL,
    64.182536,
    19.558045,
    17.5,
    'SKYE',
    'SKR1860  D/A/X',
    NULL,
    NULL,
    46434,
    858.6,
    37.2,
    25,
    NULL,
    180,
    'incoming',
    '?',
    'Up_860_1_Avg',
    NULL,
    NULL,
    NULL
  );

INSERT INTO mspectral_sensors (
    station_id, canonical_id, legacy_name, sensor_type, ecosystem, location, status, deployment_date,
    latitude, longitude, elevation_m, brand, model, serial_number, cable_length, honxiao_number,
    center_wavelength_nm, bandwidth_nm, field_of_view_degrees, azimuth_degrees, degrees_from_nadir,
    measurement_type, usage_type, parameter_names, wavelengths_nm, sensor_pairs, comments
  ) VALUES (
    6,
    'SVB_MIR_F01_MS01_9',
    'DEG-MIR-F01',
    'SPECTRAL',
    'MIR',
    'F01',
    'Active',
    NULL,
    64.182536,
    19.558045,
    17.5,
    'SKYE',
    'SKR1860  D/A/X',
    NULL,
    NULL,
    46434,
    1640.8,
    21.8,
    25,
    NULL,
    180,
    'incoming',
    '?',
    'Up_1640_1_Avg',
    NULL,
    NULL,
    NULL
  );

INSERT INTO mspectral_sensors (
    station_id, canonical_id, legacy_name, sensor_type, ecosystem, location, status, deployment_date,
    latitude, longitude, elevation_m, brand, model, serial_number, cable_length, honxiao_number,
    center_wavelength_nm, bandwidth_nm, field_of_view_degrees, azimuth_degrees, degrees_from_nadir,
    measurement_type, usage_type, parameter_names, wavelengths_nm, sensor_pairs, comments
  ) VALUES (
    6,
    'SVB_MIR_F01_MS01_10',
    'DEG-MIR-F01',
    'SPECTRAL',
    'MIR',
    'F01',
    'Active',
    NULL,
    64.182536,
    19.558045,
    17.5,
    'SKYE',
    'SKR1860  D/A/X',
    NULL,
    NULL,
    46434,
    NULL,
    NULL,
    25,
    NULL,
    180,
    'incoming',
    '?',
    'Up_Temp_18m_1_Var',
    NULL,
    NULL,
    NULL
  );

INSERT INTO mspectral_sensors (
    station_id, canonical_id, legacy_name, sensor_type, ecosystem, location, status, deployment_date,
    latitude, longitude, elevation_m, brand, model, serial_number, cable_length, honxiao_number,
    center_wavelength_nm, bandwidth_nm, field_of_view_degrees, azimuth_degrees, degrees_from_nadir,
    measurement_type, usage_type, parameter_names, wavelengths_nm, sensor_pairs, comments
  ) VALUES (
    6,
    'SVB_MIR_F01_MS01_11',
    'DEG-MIR-F01',
    'SPECTRAL',
    'MIR',
    'F01',
    'Active',
    NULL,
    64.182536,
    19.558045,
    17.5,
    'SKYE',
    'SKR1850',
    NULL,
    NULL,
    43009,
    531,
    NULL,
    25,
    317,
    45,
    'outgoing',
    'PRI',
    'Dw_531_18m_2_Avg',
    NULL,
    NULL,
    'old'
  );

INSERT INTO mspectral_sensors (
    station_id, canonical_id, legacy_name, sensor_type, ecosystem, location, status, deployment_date,
    latitude, longitude, elevation_m, brand, model, serial_number, cable_length, honxiao_number,
    center_wavelength_nm, bandwidth_nm, field_of_view_degrees, azimuth_degrees, degrees_from_nadir,
    measurement_type, usage_type, parameter_names, wavelengths_nm, sensor_pairs, comments
  ) VALUES (
    6,
    'SVB_MIR_F01_MS01_12',
    'DEG-MIR-F01',
    'SPECTRAL',
    'MIR',
    'F01',
    'Active',
    NULL,
    64.182536,
    19.558045,
    17.5,
    'SKYE',
    'SKR1850',
    NULL,
    NULL,
    43009,
    570,
    NULL,
    25,
    317,
    45,
    'outgoing',
    'PRI',
    'Dw_570_18m_2_Avg',
    NULL,
    NULL,
    'old'
  );

INSERT INTO mspectral_sensors (
    station_id, canonical_id, legacy_name, sensor_type, ecosystem, location, status, deployment_date,
    latitude, longitude, elevation_m, brand, model, serial_number, cable_length, honxiao_number,
    center_wavelength_nm, bandwidth_nm, field_of_view_degrees, azimuth_degrees, degrees_from_nadir,
    measurement_type, usage_type, parameter_names, wavelengths_nm, sensor_pairs, comments
  ) VALUES (
    6,
    'SVB_MIR_F01_MS01_13',
    'DEG-MIR-F01',
    'SPECTRAL',
    'MIR',
    'F01',
    'Active',
    NULL,
    64.182536,
    19.558045,
    17.5,
    'SKYE',
    'SKR1850',
    NULL,
    NULL,
    43009,
    620,
    NULL,
    25,
    317,
    45,
    'outgoing',
    'NDVI',
    'Dw_645_18m_2_Avg',
    NULL,
    NULL,
    'old'
  );

INSERT INTO mspectral_sensors (
    station_id, canonical_id, legacy_name, sensor_type, ecosystem, location, status, deployment_date,
    latitude, longitude, elevation_m, brand, model, serial_number, cable_length, honxiao_number,
    center_wavelength_nm, bandwidth_nm, field_of_view_degrees, azimuth_degrees, degrees_from_nadir,
    measurement_type, usage_type, parameter_names, wavelengths_nm, sensor_pairs, comments
  ) VALUES (
    6,
    'SVB_MIR_F01_MS01_14',
    'DEG-MIR-F01',
    'SPECTRAL',
    'MIR',
    'F01',
    'Active',
    NULL,
    64.182536,
    19.558045,
    17.5,
    'SKYE',
    'SKR1850',
    NULL,
    NULL,
    43009,
    841,
    NULL,
    25,
    317,
    45,
    'outgoing',
    'NDVI',
    'Dw_858_18m_2_Avg',
    NULL,
    NULL,
    'old'
  );

INSERT INTO mspectral_sensors (
    station_id, canonical_id, legacy_name, sensor_type, ecosystem, location, status, deployment_date,
    latitude, longitude, elevation_m, brand, model, serial_number, cable_length, honxiao_number,
    center_wavelength_nm, bandwidth_nm, field_of_view_degrees, azimuth_degrees, degrees_from_nadir,
    measurement_type, usage_type, parameter_names, wavelengths_nm, sensor_pairs, comments
  ) VALUES (
    6,
    'SVB_MIR_F01_MS01_15',
    'DEG-MIR-F01',
    'SPECTRAL',
    'MIR',
    'F01',
    'Active',
    NULL,
    64.182536,
    19.558045,
    17.5,
    'SKYE',
    'SKR1850',
    NULL,
    NULL,
    43010,
    531,
    NULL,
    25,
    NULL,
    180,
    'incoming',
    'PRI',
    'Up_531_18m_2_Avg',
    NULL,
    NULL,
    'old'
  );

INSERT INTO mspectral_sensors (
    station_id, canonical_id, legacy_name, sensor_type, ecosystem, location, status, deployment_date,
    latitude, longitude, elevation_m, brand, model, serial_number, cable_length, honxiao_number,
    center_wavelength_nm, bandwidth_nm, field_of_view_degrees, azimuth_degrees, degrees_from_nadir,
    measurement_type, usage_type, parameter_names, wavelengths_nm, sensor_pairs, comments
  ) VALUES (
    6,
    'SVB_MIR_F01_MS01_16',
    'DEG-MIR-F01',
    'SPECTRAL',
    'MIR',
    'F01',
    'Active',
    NULL,
    64.182536,
    19.558045,
    17.5,
    'SKYE',
    'SKR1850',
    NULL,
    NULL,
    43010,
    570,
    NULL,
    25,
    NULL,
    180,
    'incoming',
    'PRI',
    'Up_570_18m_2_Avg',
    NULL,
    NULL,
    'old'
  );

INSERT INTO mspectral_sensors (
    station_id, canonical_id, legacy_name, sensor_type, ecosystem, location, status, deployment_date,
    latitude, longitude, elevation_m, brand, model, serial_number, cable_length, honxiao_number,
    center_wavelength_nm, bandwidth_nm, field_of_view_degrees, azimuth_degrees, degrees_from_nadir,
    measurement_type, usage_type, parameter_names, wavelengths_nm, sensor_pairs, comments
  ) VALUES (
    6,
    'SVB_MIR_F01_MS01_17',
    'DEG-MIR-F01',
    'SPECTRAL',
    'MIR',
    'F01',
    'Active',
    NULL,
    64.182536,
    19.558045,
    17.5,
    'SKYE',
    'SKR1850',
    NULL,
    NULL,
    43010,
    620,
    NULL,
    25,
    NULL,
    180,
    'incoming',
    'NDVI',
    'Up_645_18m_2_Avg',
    NULL,
    NULL,
    'old'
  );

INSERT INTO mspectral_sensors (
    station_id, canonical_id, legacy_name, sensor_type, ecosystem, location, status, deployment_date,
    latitude, longitude, elevation_m, brand, model, serial_number, cable_length, honxiao_number,
    center_wavelength_nm, bandwidth_nm, field_of_view_degrees, azimuth_degrees, degrees_from_nadir,
    measurement_type, usage_type, parameter_names, wavelengths_nm, sensor_pairs, comments
  ) VALUES (
    6,
    'SVB_MIR_F01_MS01_18',
    'DEG-MIR-F01',
    'SPECTRAL',
    'MIR',
    'F01',
    'Active',
    NULL,
    64.182536,
    19.558045,
    17.5,
    'SKYE',
    'SKR1850',
    NULL,
    NULL,
    43010,
    841,
    NULL,
    25,
    NULL,
    180,
    'incoming',
    'NDVI',
    'Up_858_18m_2_Avg',
    NULL,
    NULL,
    'old'
  );

INSERT INTO mspectral_sensors (
    station_id, canonical_id, legacy_name, sensor_type, ecosystem, location, status, deployment_date,
    latitude, longitude, elevation_m, brand, model, serial_number, cable_length, honxiao_number,
    center_wavelength_nm, bandwidth_nm, field_of_view_degrees, azimuth_degrees, degrees_from_nadir,
    measurement_type, usage_type, parameter_names, wavelengths_nm, sensor_pairs, comments
  ) VALUES (
    6,
    'SVB_MIR_F01_MS01_19',
    'DEG-MIR-F01',
    'SPECTRAL',
    'MIR',
    'F01',
    'Active',
    NULL,
    64.182536,
    19.558045,
    17.5,
    'Decagon',
    'SRS-Ni',
    NULL,
    NULL,
    3,
    650,
    NULL,
    36,
    NULL,
    180,
    'incoming',
    'NDVI',
    'Up_650_2_Avg',
    NULL,
    NULL,
    NULL
  );

INSERT INTO mspectral_sensors (
    station_id, canonical_id, legacy_name, sensor_type, ecosystem, location, status, deployment_date,
    latitude, longitude, elevation_m, brand, model, serial_number, cable_length, honxiao_number,
    center_wavelength_nm, bandwidth_nm, field_of_view_degrees, azimuth_degrees, degrees_from_nadir,
    measurement_type, usage_type, parameter_names, wavelengths_nm, sensor_pairs, comments
  ) VALUES (
    6,
    'SVB_MIR_F01_MS01_20',
    'DEG-MIR-F01',
    'SPECTRAL',
    'MIR',
    'F01',
    'Active',
    NULL,
    64.182536,
    19.558045,
    17.5,
    'Decagon',
    'SRS-Ni',
    NULL,
    NULL,
    3,
    860,
    NULL,
    36,
    NULL,
    180,
    'incoming',
    'NDVI',
    'Up_860_2_Avg',
    NULL,
    NULL,
    NULL
  );

INSERT INTO mspectral_sensors (
    station_id, canonical_id, legacy_name, sensor_type, ecosystem, location, status, deployment_date,
    latitude, longitude, elevation_m, brand, model, serial_number, cable_length, honxiao_number,
    center_wavelength_nm, bandwidth_nm, field_of_view_degrees, azimuth_degrees, degrees_from_nadir,
    measurement_type, usage_type, parameter_names, wavelengths_nm, sensor_pairs, comments
  ) VALUES (
    6,
    'SVB_MIR_F01_MS01_21',
    'DEG-MIR-F01',
    'SPECTRAL',
    'MIR',
    'F01',
    'Active',
    NULL,
    64.182536,
    19.558045,
    17.5,
    'Decagon',
    'SRS-Nr',
    NULL,
    NULL,
    3,
    650,
    NULL,
    36,
    317,
    45,
    'outgoing',
    'NDVI',
    'Dw_650_2_Avg',
    NULL,
    NULL,
    NULL
  );

INSERT INTO mspectral_sensors (
    station_id, canonical_id, legacy_name, sensor_type, ecosystem, location, status, deployment_date,
    latitude, longitude, elevation_m, brand, model, serial_number, cable_length, honxiao_number,
    center_wavelength_nm, bandwidth_nm, field_of_view_degrees, azimuth_degrees, degrees_from_nadir,
    measurement_type, usage_type, parameter_names, wavelengths_nm, sensor_pairs, comments
  ) VALUES (
    6,
    'SVB_MIR_F01_MS01_22',
    'DEG-MIR-F01',
    'SPECTRAL',
    'MIR',
    'F01',
    'Active',
    NULL,
    64.182536,
    19.558045,
    17.5,
    'Decagon',
    'SRS-Nr',
    NULL,
    NULL,
    3,
    860,
    NULL,
    36,
    317,
    45,
    'outgoing',
    'NDVI',
    'Dw_860_2_Avg',
    NULL,
    NULL,
    NULL
  );

INSERT INTO mspectral_sensors (
    station_id, canonical_id, legacy_name, sensor_type, ecosystem, location, status, deployment_date,
    latitude, longitude, elevation_m, brand, model, serial_number, cable_length, honxiao_number,
    center_wavelength_nm, bandwidth_nm, field_of_view_degrees, azimuth_degrees, degrees_from_nadir,
    measurement_type, usage_type, parameter_names, wavelengths_nm, sensor_pairs, comments
  ) VALUES (
    6,
    'SVB_MIR_F01_MS01_23',
    'DEG-MIR-F01',
    'SPECTRAL',
    'MIR',
    'F01',
    'Active',
    NULL,
    64.182536,
    19.558045,
    17.5,
    'Decagon',
    'SRS-Pi',
    NULL,
    NULL,
    1,
    532,
    NULL,
    36,
    NULL,
    180,
    'incoming',
    'PRI',
    'Up_532_2_Avg',
    NULL,
    NULL,
    NULL
  );

INSERT INTO mspectral_sensors (
    station_id, canonical_id, legacy_name, sensor_type, ecosystem, location, status, deployment_date,
    latitude, longitude, elevation_m, brand, model, serial_number, cable_length, honxiao_number,
    center_wavelength_nm, bandwidth_nm, field_of_view_degrees, azimuth_degrees, degrees_from_nadir,
    measurement_type, usage_type, parameter_names, wavelengths_nm, sensor_pairs, comments
  ) VALUES (
    6,
    'SVB_MIR_F01_MS01_24',
    'DEG-MIR-F01',
    'SPECTRAL',
    'MIR',
    'F01',
    'Active',
    NULL,
    64.182536,
    19.558045,
    17.5,
    'Decagon',
    'SRS-Pi',
    NULL,
    NULL,
    1,
    570,
    NULL,
    36,
    NULL,
    180,
    'incoming',
    'PRI',
    'Up_570_2_Avg',
    NULL,
    NULL,
    NULL
  );

INSERT INTO mspectral_sensors (
    station_id, canonical_id, legacy_name, sensor_type, ecosystem, location, status, deployment_date,
    latitude, longitude, elevation_m, brand, model, serial_number, cable_length, honxiao_number,
    center_wavelength_nm, bandwidth_nm, field_of_view_degrees, azimuth_degrees, degrees_from_nadir,
    measurement_type, usage_type, parameter_names, wavelengths_nm, sensor_pairs, comments
  ) VALUES (
    6,
    'SVB_MIR_F01_MS01_25',
    'DEG-MIR-F01',
    'SPECTRAL',
    'MIR',
    'F01',
    'Active',
    NULL,
    64.182536,
    19.558045,
    17.5,
    'Decagon',
    'SRS-Pr',
    NULL,
    NULL,
    1,
    532,
    NULL,
    36,
    317,
    45,
    'outgoing',
    'PRI',
    'Dw_532_2_Avg',
    NULL,
    NULL,
    NULL
  );

INSERT INTO mspectral_sensors (
    station_id, canonical_id, legacy_name, sensor_type, ecosystem, location, status, deployment_date,
    latitude, longitude, elevation_m, brand, model, serial_number, cable_length, honxiao_number,
    center_wavelength_nm, bandwidth_nm, field_of_view_degrees, azimuth_degrees, degrees_from_nadir,
    measurement_type, usage_type, parameter_names, wavelengths_nm, sensor_pairs, comments
  ) VALUES (
    6,
    'SVB_MIR_F01_MS01_26',
    'DEG-MIR-F01',
    'SPECTRAL',
    'MIR',
    'F01',
    'Active',
    NULL,
    64.182536,
    19.558045,
    17.5,
    'Decagon',
    'SRS-Pr',
    NULL,
    NULL,
    1,
    570,
    NULL,
    36,
    317,
    45,
    'outgoing',
    'PRI',
    'Dw_570_2_Avg',
    NULL,
    NULL,
    NULL
  );

INSERT INTO mspectral_sensors (
    station_id, canonical_id, legacy_name, sensor_type, ecosystem, location, status, deployment_date,
    latitude, longitude, elevation_m, brand, model, serial_number, cable_length, honxiao_number,
    center_wavelength_nm, bandwidth_nm, field_of_view_degrees, azimuth_degrees, degrees_from_nadir,
    measurement_type, usage_type, parameter_names, wavelengths_nm, sensor_pairs, comments
  ) VALUES (
    6,
    'SVB_MIR_F01_MS01_27',
    'DEG-MIR-F01',
    'SPECTRAL',
    'MIR',
    'F01',
    'Active',
    NULL,
    NULL,
    NULL,
    NULL,
    'Licor',
    NULL,
    NULL,
    NULL,
    NULL,
    400,
    NULL,
    NULL,
    NULL,
    180,
    'incoming',
    'PAR',
    NULL,
    NULL,
    NULL,
    'installed in 2024'
  );

INSERT INTO mspectral_sensors (
    station_id, canonical_id, legacy_name, sensor_type, ecosystem, location, status, deployment_date,
    latitude, longitude, elevation_m, brand, model, serial_number, cable_length, honxiao_number,
    center_wavelength_nm, bandwidth_nm, field_of_view_degrees, azimuth_degrees, degrees_from_nadir,
    measurement_type, usage_type, parameter_names, wavelengths_nm, sensor_pairs, comments
  ) VALUES (
    6,
    'SVB_MIR_F01_MS01_28',
    'DEG-MIR-F01',
    'SPECTRAL',
    'MIR',
    'F01',
    'Active',
    NULL,
    NULL,
    NULL,
    NULL,
    'Licor',
    NULL,
    NULL,
    NULL,
    NULL,
    400,
    NULL,
    NULL,
    NULL,
    NULL,
    'outgoing',
    'PAR',
    NULL,
    NULL,
    NULL,
    'installed in 2024'
  );

INSERT INTO mspectral_sensors (
    station_id, canonical_id, legacy_name, sensor_type, ecosystem, location, status, deployment_date,
    latitude, longitude, elevation_m, brand, model, serial_number, cable_length, honxiao_number,
    center_wavelength_nm, bandwidth_nm, field_of_view_degrees, azimuth_degrees, degrees_from_nadir,
    measurement_type, usage_type, parameter_names, wavelengths_nm, sensor_pairs, comments
  ) VALUES (
    6,
    'SVB_MIR_F01_MS01_29',
    'DEG-MIR-F01',
    'SPECTRAL',
    'MIR',
    'F01',
    'Active',
    NULL,
    NULL,
    NULL,
    NULL,
    'Licor',
    NULL,
    NULL,
    NULL,
    NULL,
    400,
    NULL,
    NULL,
    NULL,
    NULL,
    'outgoing',
    'PAR',
    NULL,
    NULL,
    NULL,
    'installed in 2024'
  );

INSERT INTO mspectral_sensors (
    station_id, canonical_id, legacy_name, sensor_type, ecosystem, location, status, deployment_date,
    latitude, longitude, elevation_m, brand, model, serial_number, cable_length, honxiao_number,
    center_wavelength_nm, bandwidth_nm, field_of_view_degrees, azimuth_degrees, degrees_from_nadir,
    measurement_type, usage_type, parameter_names, wavelengths_nm, sensor_pairs, comments
  ) VALUES (
    6,
    'SVB_FOR_F01_MS01_1',
    'SVB-FOR-F01',
    'SPECTRAL',
    'FOR',
    'F01',
    'Active',
    NULL,
    64.25611,
    19.7745,
    100,
    'SKYE',
    'SKR1860',
    NULL,
    NULL,
    46437,
    530.9,
    11.5,
    25,
    323,
    45,
    'outgoing',
    'PRI',
    'Dw_530_100m_Avg',
    NULL,
    NULL,
    'Removed 2022-10-31'
  );

INSERT INTO mspectral_sensors (
    station_id, canonical_id, legacy_name, sensor_type, ecosystem, location, status, deployment_date,
    latitude, longitude, elevation_m, brand, model, serial_number, cable_length, honxiao_number,
    center_wavelength_nm, bandwidth_nm, field_of_view_degrees, azimuth_degrees, degrees_from_nadir,
    measurement_type, usage_type, parameter_names, wavelengths_nm, sensor_pairs, comments
  ) VALUES (
    6,
    'SVB_FOR_F01_MS01_2',
    'SVB-FOR-F01',
    'SPECTRAL',
    'FOR',
    'F01',
    'Active',
    NULL,
    64.25611,
    19.7745,
    100,
    'SKYE',
    'SKR1860',
    NULL,
    NULL,
    46437,
    568.8,
    10,
    25,
    323,
    45,
    'outgoing',
    'PRI',
    'Dw_570_100m_Avg',
    NULL,
    NULL,
    'Removed 2022-10-31'
  );

INSERT INTO mspectral_sensors (
    station_id, canonical_id, legacy_name, sensor_type, ecosystem, location, status, deployment_date,
    latitude, longitude, elevation_m, brand, model, serial_number, cable_length, honxiao_number,
    center_wavelength_nm, bandwidth_nm, field_of_view_degrees, azimuth_degrees, degrees_from_nadir,
    measurement_type, usage_type, parameter_names, wavelengths_nm, sensor_pairs, comments
  ) VALUES (
    6,
    'SVB_FOR_F01_MS01_3',
    'SVB-FOR-F01',
    'SPECTRAL',
    'FOR',
    'F01',
    'Active',
    NULL,
    64.25611,
    19.7745,
    100,
    'SKYE',
    'SKR1860',
    NULL,
    NULL,
    46437,
    644.2,
    50.9,
    25,
    323,
    45,
    'outgoing',
    'NDVI',
    'Dw_644_100m_Avg',
    NULL,
    NULL,
    'Removed 2022-10-31'
  );

INSERT INTO mspectral_sensors (
    station_id, canonical_id, legacy_name, sensor_type, ecosystem, location, status, deployment_date,
    latitude, longitude, elevation_m, brand, model, serial_number, cable_length, honxiao_number,
    center_wavelength_nm, bandwidth_nm, field_of_view_degrees, azimuth_degrees, degrees_from_nadir,
    measurement_type, usage_type, parameter_names, wavelengths_nm, sensor_pairs, comments
  ) VALUES (
    6,
    'SVB_FOR_F01_MS01_4',
    'SVB-FOR-F01',
    'SPECTRAL',
    'FOR',
    'F01',
    'Active',
    NULL,
    64.25611,
    19.7745,
    100,
    'SKYE',
    'SKR1860',
    NULL,
    NULL,
    46437,
    858.8,
    38.2,
    25,
    323,
    45,
    'outgoing',
    'NDVI',
    'Dw_858_100m_Avg',
    NULL,
    NULL,
    'Removed 2022-10-31'
  );

INSERT INTO mspectral_sensors (
    station_id, canonical_id, legacy_name, sensor_type, ecosystem, location, status, deployment_date,
    latitude, longitude, elevation_m, brand, model, serial_number, cable_length, honxiao_number,
    center_wavelength_nm, bandwidth_nm, field_of_view_degrees, azimuth_degrees, degrees_from_nadir,
    measurement_type, usage_type, parameter_names, wavelengths_nm, sensor_pairs, comments
  ) VALUES (
    6,
    'SVB_FOR_F01_MS01_5',
    'SVB-FOR-F01',
    'SPECTRAL',
    'FOR',
    'F01',
    'Active',
    NULL,
    64.25611,
    19.7745,
    150,
    'SKYE',
    'SKR1860',
    NULL,
    NULL,
    46435,
    531,
    11.5,
    25,
    NULL,
    180,
    'incoming',
    'PRI',
    'Up_530_150m_Avg',
    NULL,
    NULL,
    'Removed 2022-10-31'
  );

INSERT INTO mspectral_sensors (
    station_id, canonical_id, legacy_name, sensor_type, ecosystem, location, status, deployment_date,
    latitude, longitude, elevation_m, brand, model, serial_number, cable_length, honxiao_number,
    center_wavelength_nm, bandwidth_nm, field_of_view_degrees, azimuth_degrees, degrees_from_nadir,
    measurement_type, usage_type, parameter_names, wavelengths_nm, sensor_pairs, comments
  ) VALUES (
    6,
    'SVB_FOR_F01_MS01_6',
    'SVB-FOR-F01',
    'SPECTRAL',
    'FOR',
    'F01',
    'Active',
    NULL,
    64.25611,
    19.7745,
    150,
    'SKYE',
    'SKR1860',
    NULL,
    NULL,
    46435,
    569.1,
    10,
    25,
    NULL,
    180,
    'incoming',
    'PRI',
    'Up_570_150m_Avg',
    NULL,
    NULL,
    'Removed 2022-10-31'
  );

INSERT INTO mspectral_sensors (
    station_id, canonical_id, legacy_name, sensor_type, ecosystem, location, status, deployment_date,
    latitude, longitude, elevation_m, brand, model, serial_number, cable_length, honxiao_number,
    center_wavelength_nm, bandwidth_nm, field_of_view_degrees, azimuth_degrees, degrees_from_nadir,
    measurement_type, usage_type, parameter_names, wavelengths_nm, sensor_pairs, comments
  ) VALUES (
    6,
    'SVB_FOR_F01_MS01_7',
    'SVB-FOR-F01',
    'SPECTRAL',
    'FOR',
    'F01',
    'Active',
    NULL,
    64.25611,
    19.7745,
    150,
    'SKYE',
    'SKR1860',
    NULL,
    NULL,
    46435,
    643,
    50.7,
    25,
    NULL,
    180,
    'incoming',
    'NDVI',
    'Up_644_150m_Avg',
    NULL,
    NULL,
    'Removed 2022-10-31'
  );

INSERT INTO mspectral_sensors (
    station_id, canonical_id, legacy_name, sensor_type, ecosystem, location, status, deployment_date,
    latitude, longitude, elevation_m, brand, model, serial_number, cable_length, honxiao_number,
    center_wavelength_nm, bandwidth_nm, field_of_view_degrees, azimuth_degrees, degrees_from_nadir,
    measurement_type, usage_type, parameter_names, wavelengths_nm, sensor_pairs, comments
  ) VALUES (
    6,
    'SVB_FOR_F01_MS01_8',
    'SVB-FOR-F01',
    'SPECTRAL',
    'FOR',
    'F01',
    'Active',
    NULL,
    64.25611,
    19.7745,
    150,
    'SKYE',
    'SKR1860',
    NULL,
    NULL,
    46435,
    858.3,
    39.4,
    25,
    NULL,
    180,
    'incoming',
    'NDVI',
    'Up_858_150m_Avg',
    NULL,
    NULL,
    'Removed 2022-10-31'
  );

INSERT INTO mspectral_sensors (
    station_id, canonical_id, legacy_name, sensor_type, ecosystem, location, status, deployment_date,
    latitude, longitude, elevation_m, brand, model, serial_number, cable_length, honxiao_number,
    center_wavelength_nm, bandwidth_nm, field_of_view_degrees, azimuth_degrees, degrees_from_nadir,
    measurement_type, usage_type, parameter_names, wavelengths_nm, sensor_pairs, comments
  ) VALUES (
    6,
    'SVB_FOR_F01_MS01_9',
    'SVB-FOR-F01',
    'SPECTRAL',
    'FOR',
    'F01',
    'Active',
    NULL,
    64.25611,
    19.7745,
    100,
    'SKYE',
    1840,
    52998,
    NULL,
    NULL,
    650.4,
    45.2,
    25,
    323,
    45,
    'outgoing',
    'NDVI',
    'Dw_650_100m_Avg',
    NULL,
    NULL,
    'Mounted on tall tower'
  );

INSERT INTO mspectral_sensors (
    station_id, canonical_id, legacy_name, sensor_type, ecosystem, location, status, deployment_date,
    latitude, longitude, elevation_m, brand, model, serial_number, cable_length, honxiao_number,
    center_wavelength_nm, bandwidth_nm, field_of_view_degrees, azimuth_degrees, degrees_from_nadir,
    measurement_type, usage_type, parameter_names, wavelengths_nm, sensor_pairs, comments
  ) VALUES (
    6,
    'SVB_FOR_F01_MS01_10',
    'SVB-FOR-F01',
    'SPECTRAL',
    'FOR',
    'F01',
    'Active',
    NULL,
    64.25611,
    19.7745,
    100,
    'SKYE',
    1840,
    52998,
    NULL,
    NULL,
    805.5,
    34.4,
    25,
    323,
    45,
    'outgoing',
    'NDVI',
    'Dw_805_100m_Avg',
    NULL,
    NULL,
    'Mounted on tall tower'
  );

INSERT INTO mspectral_sensors (
    station_id, canonical_id, legacy_name, sensor_type, ecosystem, location, status, deployment_date,
    latitude, longitude, elevation_m, brand, model, serial_number, cable_length, honxiao_number,
    center_wavelength_nm, bandwidth_nm, field_of_view_degrees, azimuth_degrees, degrees_from_nadir,
    measurement_type, usage_type, parameter_names, wavelengths_nm, sensor_pairs, comments
  ) VALUES (
    6,
    'SVB_FOR_F01_MS01_11',
    'SVB-FOR-F01',
    'SPECTRAL',
    'FOR',
    'F01',
    'Active',
    NULL,
    64.25611,
    19.7745,
    150,
    'SKYE',
    1840,
    52997,
    NULL,
    NULL,
    649.6,
    44.7,
    25,
    NULL,
    180,
    'incoming',
    'NDVI',
    'Up_650_150m_Avg',
    NULL,
    NULL,
    'Mounted on tall tower'
  );

INSERT INTO mspectral_sensors (
    station_id, canonical_id, legacy_name, sensor_type, ecosystem, location, status, deployment_date,
    latitude, longitude, elevation_m, brand, model, serial_number, cable_length, honxiao_number,
    center_wavelength_nm, bandwidth_nm, field_of_view_degrees, azimuth_degrees, degrees_from_nadir,
    measurement_type, usage_type, parameter_names, wavelengths_nm, sensor_pairs, comments
  ) VALUES (
    6,
    'SVB_FOR_F01_MS01_12',
    'SVB-FOR-F01',
    'SPECTRAL',
    'FOR',
    'F01',
    'Active',
    NULL,
    64.25611,
    19.7745,
    150,
    'SKYE',
    1840,
    52997,
    NULL,
    NULL,
    804.2,
    34.4,
    25,
    NULL,
    180,
    'incoming',
    'NDVI',
    'Up_804_150m_Avg',
    NULL,
    NULL,
    'Mounted on tall tower'
  );

INSERT INTO mspectral_sensors (
    station_id, canonical_id, legacy_name, sensor_type, ecosystem, location, status, deployment_date,
    latitude, longitude, elevation_m, brand, model, serial_number, cable_length, honxiao_number,
    center_wavelength_nm, bandwidth_nm, field_of_view_degrees, azimuth_degrees, degrees_from_nadir,
    measurement_type, usage_type, parameter_names, wavelengths_nm, sensor_pairs, comments
  ) VALUES (
    6,
    'SVB_FOR_F01_MS01_13',
    'SVB-FOR-F01',
    'SPECTRAL',
    'FOR',
    'F01',
    'Active',
    NULL,
    64.25640716,
    19.77406568,
    2,
    'Decagon',
    'SRS-Ni',
    NULL,
    NULL,
    2,
    NULL,
    NULL,
    36,
    NULL,
    180,
    'incoming',
    'NDVI',
    'Up_650_2m_2_Avg',
    NULL,
    NULL,
    'Mounted in a small tower below canopy'
  );

INSERT INTO mspectral_sensors (
    station_id, canonical_id, legacy_name, sensor_type, ecosystem, location, status, deployment_date,
    latitude, longitude, elevation_m, brand, model, serial_number, cable_length, honxiao_number,
    center_wavelength_nm, bandwidth_nm, field_of_view_degrees, azimuth_degrees, degrees_from_nadir,
    measurement_type, usage_type, parameter_names, wavelengths_nm, sensor_pairs, comments
  ) VALUES (
    6,
    'SVB_FOR_F01_MS01_14',
    'SVB-FOR-F01',
    'SPECTRAL',
    'FOR',
    'F01',
    'Active',
    NULL,
    64.25640716,
    19.77406568,
    2,
    'Decagon',
    'SRS-Ni',
    NULL,
    NULL,
    2,
    NULL,
    NULL,
    36,
    NULL,
    180,
    'incoming',
    'NDVI',
    'Up_860_2m_2_Avg',
    NULL,
    NULL,
    'Mounted in a small tower below canopy'
  );

INSERT INTO mspectral_sensors (
    station_id, canonical_id, legacy_name, sensor_type, ecosystem, location, status, deployment_date,
    latitude, longitude, elevation_m, brand, model, serial_number, cable_length, honxiao_number,
    center_wavelength_nm, bandwidth_nm, field_of_view_degrees, azimuth_degrees, degrees_from_nadir,
    measurement_type, usage_type, parameter_names, wavelengths_nm, sensor_pairs, comments
  ) VALUES (
    6,
    'SVB_FOR_F01_MS01_15',
    'SVB-FOR-F01',
    'SPECTRAL',
    'FOR',
    'F01',
    'Active',
    NULL,
    64.25640716,
    19.77406568,
    2,
    'Decagon',
    'SRS-Nr',
    NULL,
    NULL,
    2,
    NULL,
    NULL,
    36,
    93.989,
    45,
    'outgoing',
    'NDVI',
    'Dw_650_2m_2_Avg',
    NULL,
    NULL,
    'Mounted in a small tower below canopy'
  );

INSERT INTO mspectral_sensors (
    station_id, canonical_id, legacy_name, sensor_type, ecosystem, location, status, deployment_date,
    latitude, longitude, elevation_m, brand, model, serial_number, cable_length, honxiao_number,
    center_wavelength_nm, bandwidth_nm, field_of_view_degrees, azimuth_degrees, degrees_from_nadir,
    measurement_type, usage_type, parameter_names, wavelengths_nm, sensor_pairs, comments
  ) VALUES (
    6,
    'SVB_FOR_F01_MS01_16',
    'SVB-FOR-F01',
    'SPECTRAL',
    'FOR',
    'F01',
    'Active',
    NULL,
    64.25640716,
    19.77406568,
    2,
    'Decagon',
    'SRS-Nr',
    NULL,
    NULL,
    2,
    NULL,
    NULL,
    36,
    93.989,
    45,
    'outgoing',
    'NDVI',
    'Dw_860_2m_2_Avg',
    NULL,
    NULL,
    'Mounted in a small tower below canopy'
  );

INSERT INTO mspectral_sensors (
    station_id, canonical_id, legacy_name, sensor_type, ecosystem, location, status, deployment_date,
    latitude, longitude, elevation_m, brand, model, serial_number, cable_length, honxiao_number,
    center_wavelength_nm, bandwidth_nm, field_of_view_degrees, azimuth_degrees, degrees_from_nadir,
    measurement_type, usage_type, parameter_names, wavelengths_nm, sensor_pairs, comments
  ) VALUES (
    6,
    'SVB_FOR_F01_MS01_17',
    'SVB-FOR-F01',
    'SPECTRAL',
    'FOR',
    'F01',
    'Active',
    NULL,
    64.25642138,
    19.7739277,
    2,
    'Decagon',
    'SRS-Ni',
    NULL,
    NULL,
    1,
    NULL,
    NULL,
    36,
    NULL,
    180,
    'incoming',
    'NDVI',
    'Up_650_2m_1_Avg',
    NULL,
    NULL,
    'Mounted in a small tower below canopy'
  );

INSERT INTO mspectral_sensors (
    station_id, canonical_id, legacy_name, sensor_type, ecosystem, location, status, deployment_date,
    latitude, longitude, elevation_m, brand, model, serial_number, cable_length, honxiao_number,
    center_wavelength_nm, bandwidth_nm, field_of_view_degrees, azimuth_degrees, degrees_from_nadir,
    measurement_type, usage_type, parameter_names, wavelengths_nm, sensor_pairs, comments
  ) VALUES (
    6,
    'SVB_FOR_F01_MS01_18',
    'SVB-FOR-F01',
    'SPECTRAL',
    'FOR',
    'F01',
    'Active',
    NULL,
    64.25642138,
    19.77392779,
    2,
    'Decagon',
    'SRS-Ni',
    NULL,
    NULL,
    1,
    NULL,
    NULL,
    36,
    NULL,
    180,
    'incoming',
    'NDVI',
    'Up_860_2m_1_Avg',
    NULL,
    NULL,
    'Mounted in a small tower below canopy'
  );

INSERT INTO mspectral_sensors (
    station_id, canonical_id, legacy_name, sensor_type, ecosystem, location, status, deployment_date,
    latitude, longitude, elevation_m, brand, model, serial_number, cable_length, honxiao_number,
    center_wavelength_nm, bandwidth_nm, field_of_view_degrees, azimuth_degrees, degrees_from_nadir,
    measurement_type, usage_type, parameter_names, wavelengths_nm, sensor_pairs, comments
  ) VALUES (
    6,
    'SVB_FOR_F01_MS01_19',
    'SVB-FOR-F01',
    'SPECTRAL',
    'FOR',
    'F01',
    'Active',
    NULL,
    64.25642138,
    19.77392779,
    2,
    'Decagon',
    'SRS-Nr',
    NULL,
    NULL,
    1,
    NULL,
    NULL,
    36,
    273.989,
    45,
    'outgoing',
    'NDVI',
    'Dw_650_2m_1_Avg',
    NULL,
    NULL,
    'Mounted in a small tower below canopy'
  );

INSERT INTO mspectral_sensors (
    station_id, canonical_id, legacy_name, sensor_type, ecosystem, location, status, deployment_date,
    latitude, longitude, elevation_m, brand, model, serial_number, cable_length, honxiao_number,
    center_wavelength_nm, bandwidth_nm, field_of_view_degrees, azimuth_degrees, degrees_from_nadir,
    measurement_type, usage_type, parameter_names, wavelengths_nm, sensor_pairs, comments
  ) VALUES (
    6,
    'SVB_FOR_F01_MS01_20',
    'SVB-FOR-F01',
    'SPECTRAL',
    'FOR',
    'F01',
    'Active',
    NULL,
    64.25642138,
    19.77392779,
    2,
    'Decagon',
    'SRS-Nr',
    NULL,
    NULL,
    1,
    NULL,
    NULL,
    36,
    273.989,
    45,
    'outgoing',
    'NDVI',
    'Dw_860_2m_1_Avg',
    NULL,
    NULL,
    'Mounted in a small tower below canopy'
  );

INSERT INTO mspectral_sensors (
    station_id, canonical_id, legacy_name, sensor_type, ecosystem, location, status, deployment_date,
    latitude, longitude, elevation_m, brand, model, serial_number, cable_length, honxiao_number,
    center_wavelength_nm, bandwidth_nm, field_of_view_degrees, azimuth_degrees, degrees_from_nadir,
    measurement_type, usage_type, parameter_names, wavelengths_nm, sensor_pairs, comments
  ) VALUES (
    5,
    'SKG_FOR_F01_MS01',
    'CEN-FOR-F01',
    'SPECTRAL',
    'FOR',
    'F01',
    'Active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );

INSERT INTO mspectral_sensors (
    station_id, canonical_id, legacy_name, sensor_type, ecosystem, location, status, deployment_date,
    latitude, longitude, elevation_m, brand, model, serial_number, cable_length, honxiao_number,
    center_wavelength_nm, bandwidth_nm, field_of_view_degrees, azimuth_degrees, degrees_from_nadir,
    measurement_type, usage_type, parameter_names, wavelengths_nm, sensor_pairs, comments
  ) VALUES (
    5,
    'SKG_FOR_F02_MS01',
    'CEN-FOR-F02',
    'SPECTRAL',
    'FOR',
    'F02',
    'Active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );

INSERT INTO mspectral_sensors (
    station_id, canonical_id, legacy_name, sensor_type, ecosystem, location, status, deployment_date,
    latitude, longitude, elevation_m, brand, model, serial_number, cable_length, honxiao_number,
    center_wavelength_nm, bandwidth_nm, field_of_view_degrees, azimuth_degrees, degrees_from_nadir,
    measurement_type, usage_type, parameter_names, wavelengths_nm, sensor_pairs, comments
  ) VALUES (
    5,
    'SKG_FOR_F03_MS01',
    'CEN-FOR-F03',
    'SPECTRAL',
    'FOR',
    'F03',
    'Active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );

INSERT INTO mspectral_sensors (
    station_id, canonical_id, legacy_name, sensor_type, ecosystem, location, status, deployment_date,
    latitude, longitude, elevation_m, brand, model, serial_number, cable_length, honxiao_number,
    center_wavelength_nm, bandwidth_nm, field_of_view_degrees, azimuth_degrees, degrees_from_nadir,
    measurement_type, usage_type, parameter_names, wavelengths_nm, sensor_pairs, comments
  ) VALUES (
    5,
    'SKG_WET_F01_MS01',
    'FOL-WET-F01',
    'SPECTRAL',
    'WET',
    'F01',
    'Active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );

INSERT INTO mspectral_sensors (
    station_id, canonical_id, legacy_name, sensor_type, ecosystem, location, status, deployment_date,
    latitude, longitude, elevation_m, brand, model, serial_number, cable_length, honxiao_number,
    center_wavelength_nm, bandwidth_nm, field_of_view_degrees, azimuth_degrees, degrees_from_nadir,
    measurement_type, usage_type, parameter_names, wavelengths_nm, sensor_pairs, comments
  ) VALUES (
    5,
    'SKG_MIR_F01_MS01',
    'MYC-MIR-F01',
    'SPECTRAL',
    'MIR',
    'F01',
    'Active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );

INSERT INTO mspectral_sensors (
    station_id, canonical_id, legacy_name, sensor_type, ecosystem, location, status, deployment_date,
    latitude, longitude, elevation_m, brand, model, serial_number, cable_length, honxiao_number,
    center_wavelength_nm, bandwidth_nm, field_of_view_degrees, azimuth_degrees, degrees_from_nadir,
    measurement_type, usage_type, parameter_names, wavelengths_nm, sensor_pairs, comments
  ) VALUES (
    5,
    'SKG_FOR_STD_MS01',
    'STD-FOR-F01',
    'SPECTRAL',
    'FOR',
    'STD',
    'Active',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
  );